57387
Amsterdam/zaken-backend pull request #1014
Opened 2022-09-29 11:42 UTC by remyvdwereld

2022-09-30 09:31 UTC, Pim-020 commented on app/apps/workflow/views.py
> +            return queryset.filter(case__address__housing_corporation__in=value)
Hier zou je ergens moeten afdwingen dat value een type list is.
Als het bijvoorbeeld een string wordt krijg je gekke dingen.
verder is value beetje nietszeggend, wat is het, een adres of zo ?

2022-09-30 10:53 UTC, Pim-020 requested changes

2022-09-30 11:00 UTC, Pim-020 commented on app/apps/workflow/views.py
> +        if value:
Of dat het juist een type string is. Ik weet eigenlijk niet voor welk type je bewust gaat.

2022-09-30 12:06 UTC, remyvdwereld commented on app/apps/workflow/views.py
> +        if value:
Het framework maakt van `value` automatisch een list. De parameter in het request is een string: `&housing_corporation=6`. 

Van `value` zou ik `ids` kunnen maken? `value` wordt in alle overige filters gebruikt.

2022-10-03 11:00 UTC, merged

2022-10-03 12:25 UTC, Pim-020 commented on app/apps/workflow/views.py
> +        if value:
Als het een list is dan is een meervoud naam beter, zoals `values` of `ids` inderdaad.
Verder zou die check `if value` niet nodig moeten zijn, als value een lege list is dan wordt er ook niet gefilterd.
Dan blijft wel het return type gelijk in ieder geval.
Nu is het return type of `None` (als value leeg is) of een `Queryset`