77456
Amsterdam/zaken-backend pull request #1078
Opened 2023-04-18 19:54 UTC by remyvdwereld

2023-04-19 06:49 UTC, Pim-020 requested changes

2023-04-19 06:49 UTC, Pim-020 commented on app/apps/permits/api_queries_decos_join.py
> +                                        )
`data.get("key", None)` ==> de None is hierbij niet nodig. Als de key niet bestaat krijg je None terug van de get() method.

2023-04-19 06:49 UTC, Pim-020 commented on app/apps/permits/api_queries_decos_join.py
> +                                        )
Smeert de formatter dit uit over 3 regels ipv 1 ?

2023-04-20 09:41 UTC, remyvdwereld commented on app/apps/permits/api_queries_decos_join.py
> +                                        )
Yesss!

2023-04-20 10:37 UTC, Pim-020 approved these changes

2023-04-20 11:44 UTC, merged