Camunda
Amsterdam/zaken-backend pull request #181
Opened 2021-01-12 14:34 UTC by xavierbloemen

2021-01-13 08:56 UTC, petercuret commented on app/apps/camunda/services.py
> +        print(content)
Print mag weg

2021-01-13 15:58 UTC, petercuret requested changes

2021-01-13 15:58 UTC, petercuret commented on app/apps/camunda/services.py
> +
Hier ga je er vanuit dat de request succesvol is en dat er een response is. Zou je wat veiliger op kunnen vangen. (ik krijg hier nu een error omdat mijn request faalt en content geen id veld heeft)

2021-01-14 13:30 UTC, petercuret approved these changes

2021-01-14 13:30 UTC, xavierbloemen commented on camunda/BPMN/debrief_diagram.bpmn
> +<?xml version="1.0" encoding="UTF-8"?>
komt losse pr voor. on it!

2021-01-14 13:31 UTC, merged