identification is now not used as id
Amsterdam/zaken-backend pull request #97
Opened 2020-10-27 13:43 UTC by xavierbloemen

2020-10-27 15:50 UTC, petercuret approved these changes

2020-10-27 15:52 UTC, petercuret requested changes
Ziet er goed uit. Er zijn nu 4 unit tests die falen doordat de identification veranderd is naar pk. Zou je die nog kunnen nalopen en fixen?

2020-10-28 08:55 UTC, xavierbloemen commented
Tests zijn gefixt. check ff dat ik bij debriefings case.identifacitons -> case.id heb gemaakt

2020-10-28 09:38 UTC, petercuret approved these changes

2020-10-28 09:39 UTC, merged